### ISSUE TITLE
Channel management?

### ISSUE THREAD

**Issue by ckcollab** [ElementsProject/lightning-charge#10]
So if I create an app with charged, does it automatically open/close channels? How do you "fund" charged?

If charged apps only rely on channels opened by customers, won't that have poor connectivity to the LN graph? Shouldn't you, from your own charged app, open a channel with some large node everyone else is already connected to?

Thanks!

**Comment by shesek** [comment]
> So if I create an app with charged, does it automatically open/close channels? How do you "fund" charged?

Lightning Charge's scope is to provide a convenient, simple payment processing API. Channel management, funding and other lightning-related setup should still be conducted using c-lightning directly.

> If charged apps only rely on channels opened by customers, won't that have poor connectivity to the LN graph? Shouldn't you, from your own charged app, open a channel with some large node everyone else is already connected to?

Yes, you definitely should! After opening a channel with them, you could also push some funds to them (in exchange for an onchain payment?) to make the channel bi-directional, so that you can receive incoming payments over them and not just send outgoing ones.
