### ISSUE TITLE
Bandwidth?

### ISSUE THREAD

**Issue by johnwallco** [ElementsProject/lightning-charge#26]
I would like to give Lightning Charge a try on a cloud server, but I'm concerned about bandwidth.

**How much bandwidth should I expect to use in a month?**

Depending on how much bandwidth is needed, I may need to look into a home server for Lightning Charge.

**Comment by shesek** [comment]
Bandwidth is mostly going to be used by bitcoind and lightningd, not so much by Lightning Charge itself.

For bitcoind, this depends on the number of peers you'll be connected to and whether you run in blocksonly mode or not. For lightningd, this depends on the number of connections and channels that you'll have open. So kinda hard to say.

**Comment by johnwallco** [comment]
@shesek Gotcha. Thanks.

Is there a configuration you would recommend to keep bandwidth reasonably low?

**Comment by shesek** [comment]
With lightning, you don't really care about unconfirmed transactions, so you can run bitcoind with [`-blocksonly`](https://bitcoin.org/en/full-node#blocks-only-mode) which will significantly reduce traffic usage. From the linked page on bitcoin.org:

> **Blocks-only mode**
>
> `-blocksonly`
>
> Causes your node to stop requesting and relaying transactions unless they are part of a block and also disables listening as described above.
>
> This reduces your node’s bandwidth to the absolute minimum necessary to stay synchronized with the network, about 150 megabytes incoming data per day and about 1 megabyte of outgoing data per day, but it does mean that your node won’t see incoming transactions until they’ve received at least one confirmation.

As for lightningd itself, you can run it with `--port 0` to disable listening for incoming connections, so that the only connections are the ones you initiate. The traffic usage will vary greatly depending on the numbers of peers you connect to, the numbers of open channels, and the number of payments you make/route. But it should be quite low overall, its really mainly bitcoind that's going to use traffic here.

**Comment by johnwallco** [comment]
Awesome. I'm looking forward to trying this out. Appreciate it.
