### ISSUE TITLE
how to open a channel with the docker image: "lightning-cli: Connecting to 'lightning-rpc': Connection refused"

### ISSUE THREAD

**Issue by brandoncollins7** [ElementsProject/lightning-charge#40]
I have setup the docker image and connected to an external bitcoind through the environment variables. When I ssh into the docker box and try to run "lightning-cli getaddr" I am shown the error, "lightning-cli: Connecting to 'lightning-rpc': Connection refused". All my charge rest requests work fine, but unless I can run these commands how do I open an channel?

**Comment by shesek** [comment]
The lightning data directory is located at `/data/lightning`. This should work:

    $ lightning-cli --lightning-dir=/data/lightning getinfo

Alternatively, you can also run lightningd yourself outside of docker, then mount the data directory into `/etc/lightning`, i.e. `docker run -v $HOME/.lightning:/etc/lightning ... shesek/lightning-charge`. This will cause Charge to use your existing lightningd instance instead of spinning its own. (note that if you do that, you won't have to specify the bitcoind connection details for docker, as its only lightningd that needs to know them)

**Comment by shesek** [comment]
With the change introduced in https://github.com/ElementsProject/lightning-charge/commit/7efb5138c6f20a9b289f89b6431613432ee270e1, manually specifying the lightning data directory for `lightning-cli` should no longer be required.

Closing this, please report back if you're still having issues.
