### ISSUE TITLE
Sending a payment to the address on the invoice is never able to find a route

### ISSUE THREAD

**Issue by brandoncollins7** [ElementsProject/lightning-charge#41]
Maybe I am missing something but it seems this tool is incomplete? I have the image up and running and figured out that I had to ssh into the box and open some channels via lightning-cli manually. But even after doing this (and being able to successfully send a payment to starblocks) I am never able to find a route to receive an incoming payment. That is with both my eclair for android and my lightning-charge node being connected to the same acinq node. Given the whole point of this project appears to be accepting payments I don't see any documentation on what I could be missing to actually be able to receive the payment? It doesn't even appear this image exposes the right port for the lightningd to even be discovered?

**Comment by shesek** [comment]
>  am never able to find a route to receive an incoming payment.

Lightning channels funded by you have their entire balance initially belonging to you. In this state, you can't receive incoming payments since all the funds are already yours. Getting inbound payment capacity requires sending some funds first to balance the channel. See the [explanation here](http://lightning-wallet.com/using-lightning-wallet.html#receiving-lightning-funds) for some more details.

> exposes the right port for the lightningd

The Dockerfile [does expose this](https://github.com/ElementsProject/lightning-charge/blob/80be0a3bc4a11714e32e34be77f9babf432b954e/Dockerfile#L66), its port 9735. If you want docker to forward this, add `-p 9735:9735` to your `docker run` command.

**Comment by shesek** [comment]
Closing, please report back if you're still having trouble.
