### ISSUE TITLE
Multiple API keys

### ISSUE THREAD

**Issue by BartKnucle** [ElementsProject/lightning-charge#44]
Hi,

I would like to know if there is a plain (or if it is possible?) to create multiple api keys without runnning multiple charged instances?

Thank you!

**Comment by shesek** [comment]
Currently, each `charged` instance has a single API key associated with it.

What would you want to use multiple API keys for? Different c-lightning backends for each? Or the same backend, but isolate their access to the invoices they created? Or something else?

**Comment by BartKnucle** [comment]
Yes, the second option. I wanna be able to expose differents api key to multiple woo commerce merchants for example without having to run multiple instances of c-lightning or charged.

**Comment by shesek** [comment]
So basically, a [Strike](https://strike.acinq.co/)-like hosted solution for processing lightning payments?

This would be an interesting use-case indeed, but it is currently not possible. I don't have any specifics plans to implement this, but I think that Lightning Charge could be a great starting point for doing this.

This could possibly even be implemented as a separate daemon that sits on top Lightning Charge, that manages authentication and exposes a similar API, so that you won't have to maintain a fork and can keep pulling upstream changes.

I'm closing the issue, but feel free to comment if you have more questions.

**Comment by BartKnucle** [comment]
Thank you! I'll explore your third layer solution ;)
