### ISSUE TITLE
Change price from Bitcoin Average?

### ISSUE THREAD

**Issue by owldock** [ElementsProject/lightning-charge#71]
Bitcoin Average removed its free API, but I think that's now breaking Lightning Charge since it's trying to pull price data from that API -- could you release a new LN charge version w/a different API so it can be integrated back into BTCPay? I believe BTCPay had a similar problem and [now uses CoinGecko](https://blog.btcpayserver.org/btcpay-server-1-0-3-147/), so perhaps that's an option. Thanks!

**Comment by shesek** [comment]
This was already [implemented](https://github.com/ElementsProject/lightning-charge/commit/cdbdb0b2937a7fe57e3eb0c80ea0c202b840c4b1) and released in v0.4.16 back in Jan.

You might've encountered this because it took some more time to publish the docker images for v0.4.16, is it possible you were still using v0.4.15 because of that?

**Comment by owldock** [comment]
> You might've encountered this because it took some more time to publish the docker images for v0.4.16, is it possible you were still using v0.4.15 because of that?

Yup -- all working now after BTCPayServer update w/latest docker imgs -- thanks!!
